[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  functionsPort = 9999
  targetPort = 4321

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200